# Generated by Django 3.2.3 on 2021-05-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('A', 'Administrator'), ('B', 'Employer'), ('C', 'Employee')], default='A', max_length=1),
        ),
    ]
