# Generated by Django 3.2.3 on 2021-05-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20210520_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_employee',
            field=models.BooleanField(default=False, verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_employer',
            field=models.BooleanField(default=False, verbose_name='Employer'),
        ),
    ]
