# Generated by Django 3.2.3 on 2021-05-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20210525_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_employed',
            field=models.BooleanField(default=False, verbose_name='Employed'),
        ),
    ]
