# Generated by Django 3.2.3 on 2021-05-27 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_customuser_is_employed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_employed',
        ),
    ]
