# Generated by Django 3.2.3 on 2021-05-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_remove_customuser_is_employed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_employed',
            field=models.BooleanField(default=False, verbose_name='Employed'),
        ),
    ]
