# Generated by Django 3.2.3 on 2021-05-20 03:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0002_auto_20210520_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='salary_range',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(900000)]),
        ),
    ]
