# Generated by Django 3.2.3 on 2021-05-24 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0005_auto_20210524_0919'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobCategory',
        ),
    ]
