# Generated by Django 3.2.3 on 2021-05-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0007_jobapplication_cover_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
