# Generated by Django 3.2.3 on 2021-05-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0008_jobs_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='status',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
