# Generated by Django 3.2.3 on 2021-05-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0009_auto_20210525_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='status',
            new_name='is_accepted',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='is_declined',
            field=models.BooleanField(default=False),
        ),
    ]
