# Generated by Django 3.2.3 on 2021-05-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0010_auto_20210527_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='ee_is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ee_is_declined',
            field=models.BooleanField(default=False),
        ),
    ]
