# Generated by Django 3.2.3 on 2021-05-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0011_auto_20210527_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='salary_range',
            field=models.CharField(max_length=250),
        ),
    ]
