# Generated by Django 3.2.3 on 2021-05-28 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0013_jobs_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='resume',
        ),
    ]
