# Generated by Django 3.2.3 on 2021-06-01 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0015_alter_jobapplication_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='img',
            field=models.ImageField(default='static/image/no_image.png', upload_to='static/image/'),
        ),
    ]
